language: perl
before_install:
  - sudo add-apt-repository universe
  - sudo apt-get -qq update
  - sudo apt-get install emacs
  - sudo apt-get install -y rlwrap
  - sudo apt-get install -y colordiff  
  - sudo apt-get install -y libssl-dev
  - sudo apt-get install -y asciinema
  - cpanm Perl::Tidy
  - cpanm Perl::Critic
  - cpanm Term::ANSIColor
  - cpanm WWW::Mechanize  
install:
  - ./configure
  - ./install
  - ./install_shellcheck
script:
  - ./run_tests
env:
  - TRAVIS_GIT_COMMITS=50
