language: perl
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install emacs
  - sudo apt-get install -y rlwrap
  - sudo apt-get install -y colordiff  
  - cpanm Perl::Tidy
  - cpanm Perl::Critic
install:
  - ./configure
  - ./install
  - ./install_shellcheck
script:
  - ./run_tests
env:
  - TRAVIS_GIT_COMMITS=50
