language: perl
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y emacs24
  - sudo apt-get install -y rlwrap
  - cpanm Perl::Tidy
  - cpanm Perl::Critic
install:
  - ./configure
  - ./install
script:
  - ./run_tests
env:
  - TRAVIS_GIT_COMMITS=50
