#!/bin/bash

_install() {
    DOT_FILE=$1
    ORIGINAL="$HOME/$DOT_FILE"
    if [ -f $ORIGINAL ]; then
        SHA1_OLD=$( sha1sum $ORIGINAL | cut -f1 -d' ' )
        SHA1_NEW=$( sha1sum $DOT_FILE | cut -f1 -d' ' )
        if [ "$SHA1_OLD" == "$SHA1_NEW" ]; then
            echo "$ORIGINAL is already the latest version"
            return true
        else
            echo -e "${YELLOW}Updating $ORIGINAL$RESET"
            CMD="cp $ORIGINAL $ORIGINAL.$NOW"
            echo $CMD
            `$CMD`
        fi
    fi

    CMD="cp $DOT_FILE $ORIGINAL"
    echo $CMD
    `$CMD`
}

source .colors

DOT_FILES=(
    .bashrc
    .colors
    .emacs
    .emacs.felix.el
    .gitconfig
    .gitignore
    .inputrc
)

NOW=$( date +%s )

for DOT_FILE in ${DOT_FILES[@]}; do
    _install $DOT_FILE
done

IMAGES=(
    felix.txt
)

IMAGE_DIR="$HOME/.felix"
mkdir -p $IMAGE_DIR
for IMAGE in ${IMAGES[@]}; do
    CMD="cp .felix/$IMAGE $IMAGE_DIR"
    echo $CMD
    `$CMD`
done

exit 0
