#!/bin/bash

source .colors

_header() {
    echo '--------------------------------------------------'
}

_test_command() {
    COMMAND=$1
    echo "$COMMAND"
    echo -n "==> "
    OUTPUT=`$COMMAND 2>&1 `
    if [ $? -eq 0 ]; then
        echo "[$GREEN OK $RESET]"
    else
        echo "[$RED FAIL $RESET]"
        echo $OUTPUT
        TEST_FAILURES=$(( $TEST_FAILURES + 1 ))
    fi
    _header
    true
}

_bash_test() {
    DOT_FILE=$1
    _test_command "bash -x $DOT_FILE"
    # Not Applicable ----------> SC2148: Shebang (#!) missing. Assuming Bash.
    _test_command "shellcheck -e SC2148 $DOT_FILE"
}

echo -e "${BLUE}ShellCheck Version$RESET"
shellcheck -V
_header

echo -e "${YELLOW}Running Tests$RESET"
_header

TEST_FAILURES=0

# Actual Tests
_bash_test $HOME/.bashrc
_bash_test $HOME/.bash_install_functions
_bash_test $HOME/.colors
_bash_test $HOME/.inputrc
_test_command "emacs --script $HOME/.emacs"
_test_command "emacs --script $HOME/.emacs.felix.el"
_test_command "git config -l --file=$HOME/.gitconfig"

if [[ "$TEST_FAILURES" -gt "0" ]]; then
    echo -e "==> ${RED}Failed $TEST_FAILURES tests!$RESET"
    _header
else
    echo -e "${GREEN}==> SUCCESS! $RESET"
    _header
fi
exit $TEST_FAILURES

