#!/bin/bash

source .bash_install_functions

if ! is_redhat; then
    warning "Not Redhat!"
    exit 1
fi

YUM_PACKAGES=(
    asciinema
    colordiff
    emacs-nox
    gcc
    git
    make
    perl-App-cpanminus
    perl-CPAN
    perl-doc
    python34
    python34-setuptools
    rlwrap
    tmux
)

CPAN_PACKAGES=(
    Env
    Fatal
    File::HomeDir
    File::Which
    Pod::Spell
)

yum_install_epel_release
yum_makecache

for YUM_PACKAGE in ${YUM_PACKAGES[@]}; do
    yum_install $YUM_PACKAGE
done

for CPAN_PACKAGE in ${CPAN_PACKAGES[@]}; do
    cpan_install $CPAN_PACKAGE
done

while read CPAN_PACKAGE; do
    cpan_install $CPAN_PACKAGE
done <./common_cpan_packages

./install_shellcheck
./run_all

success

exit 0
