#!/bin/bash

source .bash_install_functions

if [[ ! is_debian ]]; then
    warning "Not Debian!"
    exit 1
fi

APT_PACKAGES=(
    asciinema
    colordiff
    emacs-nox
    gcc
    libssl-dev
    make
    perl-doc
    rlwrap
)

CPAN_PACKAGES=(
    App::cpanminus
    LWP::Protocol::https
    Perl::Critic
    Perl::Tidy
    Term::ANSIColor
    WWW::Mechanize
)

apt_update

for APT_PACKAGE in ${APT_PACKAGES[@]}; do
    apt_install $APT_PACKAGE
done

for CPAN_PACKAGE in ${CPAN_PACKAGES[@]}; do
    cpan_install $CPAN_PACKAGE
done

./install_shellcheck
./run_all

success

exit 0
